name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    uses: FloatingMilkshake/actions/.forgejo/workflows/websites/deploy.yml@main
    with:
      ssh-host-key: ${{ vars.SSH_HOST_KEY }}
      ssh-hostname: ${{ vars.SSH_HOSTNAME }}
    secrets:
      ts-auth-key: ${{ secrets.TS_AUTH_KEY }}
      ssh-key: ${{ secrets.SSH_KEY }}
